### ISSUE TITLE
Open links in comments

### ISSUE THREAD

**Issue by licaon-kter** [labnex/LabNex#11]
...now they are just text

**Comment by mmarif4u** [comment]
Can you please elaborate on which screen it is? In the issue's listing, every card is clickable.

**Comment by licaon-kter** [comment]
when you read an issue and somebody wrote/pasted a link, you can't click on that link

**Comment by mmarif4u** [comment]
Okay, got it. Internal links should resolve and open in the app, but it’s not fully implemented yet.
