### ISSUE TITLE
The app crashes on sign in

### ISSUE THREAD

**Issue by kannanvm** [labnex/LabNex#33]
**I confirm that I have searched the issue tracker**
Before opening an issue, take a few minutes to search the issue tracker (both open and closed issues) for the problem you are facing. This will reduce the need for issue triage and save time.

 - [x] I confirm that I have searched the issue tracker

**Describe the bug**
On submitting the URL and access token the application is crashing immediately. It seems the request is not being sent to the server.

**Versions (please complete the following information)**
 - LabNex:  2.0.0
 - Android:  11
 - GitLab:  

**GitLab instance**
 - [x] gitlab.com
 - [ ] framagit.org
 - [ ] Self-hosted instance
 - [ ] Other service (Name/URL: )

**Mode of installation**
 - [ ] Google Play Store
 - [x] F-droid
 - [ ] APK
 - [ ] Built from source
 - [ ] OpenAPK
 - [ ] Other stores (Name: )

**Comment by kannanvm** [comment]
I might've typed the access token wrong, but it should've given an authentication error. Is it possible the issue is related to input support?

**Comment by mmarif4u** [comment]
There is an authentication error when the token is wrong/invalid/expired etc.

What input support do you have?

**Comment by kannanvm** [comment]
> What input support do you have?

I mean, is it possible the app crashed because of unsupported characters. I might've used some unicode character instead of "-".

**Comment by mmarif4u** [comment]
It could be, I haven't tested with it. I will check on it.

That's why it is recommended to type the token or double-check it when copy/pasting it.

Is your issue now resolved after fixing the token?

**Comment by kannanvm** [comment]
Yes, it was fixed after passing correct token.
